stages:
  - test
  - build
  - deploy

lint:
  image: node:hydrogen-alpine3.18
  stage: test
  except:
    - master
    - tags
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - node_modules
  before_script:
    - npm install -g pnpm
    - pnpm install --no-frozen-lockfile
  script:
    - pnpm lint
    - pnpm nuxi typecheck
  allow_failure: true

.build:
  stage: build
  image: docker:19.03
  tags:
    - builder
    - shared
    - snowdog
  before_script:
    - apk add curl
    - mkdir -p ~/.docker/cli-plugins
    - curl -o ~/.docker/cli-plugins/docker-buildx -L https://github.com/docker/buildx/releases/download/v0.6.3/buildx-v0.6.3.linux-amd64
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - >
      if [ $BUILD_TYPE = "tag" ]; then
        export IMAGE_TAG="CI_COMMIT_TAG"
      else
        export IMAGE_TAG="${CI_COMMIT_REF_SLUG}"
      fi
    - >
      docker buildx build
      --cache-from=type=local,src=/cache
      --cache-to=type=local,mode=max,dest=/cache
      --target server
      --tag "${CI_REGISTRY_IMAGE}/server:${IMAGE_TAG}"
      --push .

.deploy:
  stage: deploy
  image: docker:24.0
  variables:
    GIT_STRATEGY: none
    STACK_NAME: a11y
    SERVICE_NAME: app
    ENVIRONMENT: stage
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker pull "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
  script:
    - docker service update "${STACK_NAME}_${SERVICE_NAME}_${ENVIRONMENT}" --force --with-registry-auth --image "$CI_REGISTRY_IMAGE:$IMAGE_TAG"


build:stage:
  extends: .build
  variables:
    BUILD_TYPE: branch
  only:
    - master

build:test:
  extends: .build
  variables:
    BUILD_TYPE: branch
  only:
    - test

build:prod:
  extends: .build
  variables:
    BUILD_TYPE: tag
  only:
    - tags

deploy:stage:
  extends: .deploy
  variables:
    IMAGE_TAG: "${CI_COMMIT_REF_SLUG}"
    ENVIRONMENT: stage
  tags:
    - a11y
    - deploy
    - runner
  only:
    - master

deploy:test:
  extends: .deploy
  variables:
    IMAGE_TAG: "${CI_COMMIT_REF_SLUG}"
    ENVIRONMENT: test
  tags:
    - a11y
    - deploy
    - runner
  only:
    - test
