<script setup lang="ts">
import type { Database } from 'types/supabase'
import type { UserClaim } from 'types/user'

definePageMeta({
  middleware: 'auth',
})

const user = useSupabaseUser()
const client = useSupabaseAuthClient()
const supabase = useSupabaseClient<Database>()
const audits = ref<Database['public']['Tables']['audits']['Row'][]>([])

const { data: isAdmin } = await client.rpc('is_claims_admin')

const { data: claims } = (await supabase.rpc('get_my_claims')) as unknown as {
  data: UserClaim
}
const isAuditor = claims?.user_role === 'auditor'

if (user.value) {
  await fetchAudits()
}

async function fetchAudits() {
  const { data } = await supabase.from('audits').select('*')
  // @todo: fix possibly infinite issue for issues `Json` type
  // @note: temporary disabled - types are generated by supabase
  // @ts-ignore: possibly infinite issue
  audits.value = data || []
}
</script>

<template>
  <div class="grid">
    <div class="flex justify-between">
      <h1>Audit list</h1>

      <NuxtLink
        v-if="isAdmin || isAuditor"
        to="/audit/new"
        class="p-button-link"
      >
        Add new audit
      </NuxtLink>
    </div>

    <div class="grid">
      <ul v-if="audits.length">
        <li
          v-for="{ id, profile_id, created_at, issues, status } in audits"
          :key="id"
        >
          <Card
            :pt="{
              content: {
                class: 'flex flex-col',
              },
            }"
            class="mb-6"
          >
            <template #content>
              <span>Id: {{ id }}</span>
              <span>Status: {{ status }}</span>
              <span>Results: {{ issues }}</span>
              <span
                >Created:
                {{ new Date(created_at).toLocaleDateString('pl-PL') }}</span
              >
              <strong
                v-if="profile_id === user?.id"
                class="underline"
              >
                is yours
              </strong>
            </template>

            <template #footer>
              <NuxtLink :to="`/audit/edit/${id}`"> Edit </NuxtLink>
            </template>
          </Card>
        </li>
      </ul>
      <p v-else>Your audit list is empty</p>
    </div>
  </div>
</template>
