<script setup lang="ts">
import { useToast } from 'primevue/usetoast'
import type { Database } from 'types/supabase'
import type { Audit } from 'types/database'

definePageMeta({
  middleware: 'auth',
})

const { isAdmin, isAuditor } = useUser()
const supabase = useSupabaseClient<Database>()
const audits = ref<Audit[]>([])
const toast = new useToast()

await fetchAudits()

async function fetchAudits() {
  const { data } = await supabase
    .from('extended_audits')
    .select('*, axe (id)')
    .order('created_at', { ascending: false })
  // @todo: fix possibly infinite issue for issues `Json` type
  // @note: temporary disabled - types are generated by supabase
  // @ts-ignore: possibly infinite issue
  audits.value = data || []
}

const deleteAudit = async (auditId) => {
  const { error } = await supabase.from('audits').delete().eq('id', auditId)
  if (!error) {
    audits.value = audits.value.filter(({ id }) => id !== auditId)

    toast.add({
      severity: 'success',
      summary: `Audit #${auditId} deleted`,
      life: 3000,
    })
  }
}
</script>

<template>
  <div class="grid">
    <div class="flex justify-between">
      <h1>Audit list</h1>

      <NuxtLink
        v-if="isAdmin || isAuditor"
        to="/audit/new"
        class="p-button-link"
      >
        Add new audit
      </NuxtLink>
    </div>

    <div class="grid">
      <Card
        :pt="{
          content: {
            class: 'flex flex-col',
          },
        }"
        class="mb-6"
      >
        <template #content>
          <AuditTable
            v-if="audits.length"
            :audits="audits"
            @delete-audit="deleteAudit"
          />
          <p v-else>Your audit list is empty</p>
        </template>
      </Card>
    </div>
  </div>
</template>
