{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "chart.fullname" . }}
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  {{- with .Values.hpa.metrics }}
  metrics:
  {{- if .cpu.enabled }}
  - type: Resource
    resource:
      name: cpu
      target: {{ .cpu.target | toYaml | nindent 8 }}
  {{- end }}
  {{- if .memory.enabled }}
  - type: Resource
    resource:
      name: memory
      target: {{ .memory.target | toYaml | nindent 8 }}
  {{- end }}
  {{- end }}
{{- end -}}
