{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "chart.fullname" .}}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    {{- range .Values.ingressRoute.whitelistedIPs }}
  - kind: Rule
    match: Host(`{{ $.Values.ingressRoute.host }}`) && PathPrefix(`/`) && ClientIP(`{{ . }}`)
    middlewares:
    services:
      - kind: Service
        name: {{ include "chart.fullname" $ }}
        port: 80
    {{- end }}
  - kind: Rule
    match: Host(`{{ .Values.ingressRoute.host }}`) && PathPrefix(`/`)
    {{- if .Values.ingressRoute.basicAuth.enabled }}
    middlewares:
      - name: {{ include "chart.fullname" . }}-basic-auth
    {{- end }}
    services:
      - kind: Service
        name: {{ include "chart.fullname" . }}
        port: 80
{{- end }}
