{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "chart.fullname" . }}
            port:
              name: {{ .Values.service.portName }}
        path: /
        pathType: Prefix
{{- end }}
