{{- if .Values.ingressRoute.basicAuth.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "chart.fullname" . }}-basic-auth
spec:
  basicAuth:
    secret: {{ include "chart.fullname" . }}-basic-auth
{{- end }}
