apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
data:
  {{- if .Values.secrets.data }}
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc }} 
  {{- end }}
  {{- end }}
