<script setup lang="ts">
import type { ExtendedAudit, Project } from 'types/database'
import type { Database } from 'types/supabase'

definePageMeta({
  middleware: 'auth',
})

const { user, isViewer } = useUser()
const projects = ref<Project[]>([])
const audits = ref<ExtendedAudit[]>([])
const isLoading = ref(true)

async function fetchProjects() {
  const supabase = useSupabaseClient<Database>()

  try {
    const { data } = await supabase
      .from('projects')
      .select('*', { count: 'exact' })
      .order('created_at', { ascending: true })
    projects.value = data || []
  } catch (error) {
    console.error('Error fetching projects:', error)
  }
}

async function fetchAudits() {
  const supabase = useSupabaseClient<Database>()

  const { data } = await supabase
    .from('audits')
    .select('*, axe (id)')
    .order('created_at', { ascending: false })
    .eq('profile_id', user.value.id)

  // @todo: fix possibly infinite issue for issues `Json` type
  // @note: temporary disabled - types are generated by supabase
  // @ts-ignore: possibly infinite issue
  audits.value = data || []
}

async function fetchData() {
  try {
    await Promise.all([fetchAudits(), fetchProjects()])
  } catch (error) {
    console.error('Error fetching data:', error)
  } finally {
    isLoading.value = false
  }
}

onMounted(async () => await fetchData())
</script>

<template>
  <div class="grid grid-cols-1 space-y-8">
    <NuxtLink
      class="p-button p-button-lg justify-center md:w-2/5"
      to="/audit/new"
    >
      Create new audit
    </NuxtLink>

    <div
      class="grid gap-4"
      :class="{
        'md:w-3/5 md:grid-cols-1': isViewer,
        'md:grid-cols-2': !isViewer,
      }"
    >
      <AuditList
        v-if="!isViewer"
        :audits="audits"
        :initial-count="5"
        :is-loading="isLoading"
      />

      <ProjectList
        :projects="projects"
        :initial-count="5"
        :is-loading="isLoading"
      />
    </div>
  </div>
</template>
